language: java

sudo: false # run on container-based infrastructure

cache:
  directories:
    - $HOME/.gradle

jdk:
#  - openjdk6
  - openjdk7
  - oraclejdk8

env:
  matrix:
    - VARIANT=2.0
    - VARIANT=2.3
    - VARIANT=2.4
  global:
    # SIGNING_PASSWORD
    - secure: "GBvPdDAaMfr0iAYHzVxhMIBVHFanEPY+69CbEFijbZjhv8h0FPvuLos2p1K5/hbmNkQ1Hd2+CHsm3ErvXQHXtpXn0HmKvzSP7pnPk83iRNVGPieasvfnKiSohZeEplkAK6kbK8sZbjJRUFqUZtwyPtWfs244rCOo++D3KtfggzQ="
    # SONATYPE_OSS_USERNAME
    - secure: "anBi55oiDZyi1HojzTktATdcF63+4Ch9OQ8uZM2yAMVJdJ7hZ/m8u2ntKTpPWDbvuyN/XDLMAny5w/2B+Y2p8vztO9QDqxMNDDhzoGD2L2X0cVV6GMWnY49g+mYcmm3Y8u7dCBsjhVaP5fsW9HFL0m5cLKgyP/t80MNnSF2E+gA="
    # SONATYPE_OSS_PASSWORD
    - secure: "czpRxFlTAW7bG/IllHlJ0fMm0SNkrYV+W14LwP1Et8thIHYhkU7ugbI8v9jsgBKEMT/m1hNNMq6iV2sMQc9fqRFXyXuLw2AhvIKMJvTQJ79M7dluB8fQsH151DICNGgTnwse+bMBxYQNhL4eYBrM8syVnVtav7LGUZSB7tbZT/g="
    # GITHUB_TOKEN
    - secure: "DklZVyzWU6hpD6HOTxcncGyuHKXrRPB6d2EIDfgECMwvnIRD6fSPEVeKSWsdOadMk7gmEghFANUdDF77FvgHagMVLb0rHc6oIsXw7CL5ga4GTSr2K++E+aaplixwlRAc+oT0nkiiZ7HAOdZPSbipoMfiBYeljqJCyN0KOWSfyWI="

matrix:
  exclude:
    # Groovy 2.0 doesn't support Java 8
    - jdk: oraclejdk8
      env: VARIANT=2.0
    # Reduce Travis workload (currently 5 concurrent builds are allowed)
    # See travisCiBuild task for mandatory combinations
    - jdk: oraclejdk8
      env: VARIANT=2.3
#    - jdk: openjdk7
#      env: VARIANT=2.0
#    - jdk: openjdk7
#      env: VARIANT=2.4

install: true

#Restore before merge
script: ./gradlew prepareForTravisCiBuild -i -Dvariant=$VARIANT && ./gradlew travisCiBuild -Dvariant=$VARIANT -x test -i

notifications:
  slack:
    secure: eOht23SFXh9MayI/vIiez6pWvwYw/D92d8gvbQvRWtL4EumgA7aRW52roSCayKBg8HzYFUdylFyD2d1P8cgHBhdvIwq/aMSVa/5EsJ4fTlwJJEhS3aTPdGQqgv8XdRrE9WJ8S/yp7LbZXbEpGKKUqsjLYkTDM7SQJUJmvLz0X00=
