language: java

sudo: false # run on container-based infrastructure

cache:
  directories:
    - $HOME/.gradle

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8

env:
  matrix:
    - VARIANT=2.0
    - VARIANT=2.3
    - VARIANT=2.4
  global:
    # SIGNING_PASSWORD
    - secure: "GBvPdDAaMfr0iAYHzVxhMIBVHFanEPY+69CbEFijbZjhv8h0FPvuLos2p1K5/hbmNkQ1Hd2+CHsm3ErvXQHXtpXn0HmKvzSP7pnPk83iRNVGPieasvfnKiSohZeEplkAK6kbK8sZbjJRUFqUZtwyPtWfs244rCOo++D3KtfggzQ="
    # SONATYPE_OSS_USERNAME
    - secure: "b5c8SVcioPqKwg1IXgoqPTyJHE2LXeNwNUYHI5a1mDdZsRbphPuYHjTtRvhpVAjPKeSpocubwarna2jjnmnJ0cOa17tcBQAz8Srj6NolgiL5xjqAhDajUpDaPuDIxGfmPD+ApVNidTJovJQLA3eLI36Bzp4sdQmDEKBusCbuZcc="
    # SONATYPE_OSS_PASSWORD
    - secure: "KIrlWrB7LsWxtiRnOSCbSqXvNAitks87IBV7++sNlB5S/i3Ut+imhEKhPKv2/g0fU+j+jv9qmBd5Gq+hMKSQ8b+HMteajlfd+U39o/1zN+PJAVwtLRIQ+7n156A4dDXuVeiskjVs1ubvNUfdTsguvM4MzPaBt4XUbmzu0m0HfBU="
    # GITHUB_TOKEN
    - secure: "EyMgciFZ3s2fHRjjpMq5jA9U9SHgVD1JIcEcOpkAIvglYHDzI0gevlHCDdV9+4YRgiOUhpSAJ+jh1PuhWIOinaD8leDy068IiZxV9reu1F8jVXBb71ElayzisKmVYyMc01V+qsF/rcY1c4G84qbNBfDx+MW6SG/Ur3PYuiiNK6w="

matrix:
  exclude:
    # Groovy 2.0 doesn't support Java 8
    - jdk: oraclejdk8
      env: VARIANT=2.0
    # Reduce Travis workload (currently 5 concurrent builds are allowed)
    # See travisCiBuild task for mandatory combinations
    - jdk: oraclejdk8
      env: VARIANT=2.3
    - jdk: openjdk7
      env: VARIANT=2.0
    - jdk: openjdk7
      env: VARIANT=2.4

install: true

script: ./gradlew createRelease -i && ./gradlew travisCiBuild -Dvariant=$VARIANT

notifications:
  slack:
    secure: eOht23SFXh9MayI/vIiez6pWvwYw/D92d8gvbQvRWtL4EumgA7aRW52roSCayKBg8HzYFUdylFyD2d1P8cgHBhdvIwq/aMSVa/5EsJ4fTlwJJEhS3aTPdGQqgv8XdRrE9WJ8S/yp7LbZXbEpGKKUqsjLYkTDM7SQJUJmvLz0X00=
